version: "3.8"
services:
  backend:
    image: todo-backend
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - todo-network

  frontend:
    image: todo-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://172.188.18.5:8080
    depends_on:
      - backend
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
